=== bastianluk/MFFUK/XML Technologies/HW/03 - XML Schema/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
  <xs:element name="chain" type="TChain">
    <xs:key name="KChain">
			<xs:selector xpath="chain"></xs:selector>
			<xs:field xpath="@chainId"></xs:field>
		</xs:key>
		<xs:keyref name="FKEnterprise_Chain" refer="KChain">
			<xs:selector xpath="chain/enterprises/enterprise"></xs:selector>
			<xs:field xpath="@chainId-ref"></xs:field>
		</xs:keyref>

		<xs:key name="KChainOwner">
			<xs:selector xpath="chain/owner"></xs:selector>
			<xs:field xpath="@oId"></xs:field>
		</xs:key>
		<xs:keyref name="FKChain_Owner" refer="KChainOwner">
			<xs:selector xpath="chain"></xs:selector>
			<xs:field xpath="@ownerId-ref"></xs:field>
		</xs:keyref>
		
		<xs:key name="KEnterpriseOwner">
			<xs:selector xpath="chain/owner"></xs:selector>
			<xs:field xpath="@oId"></xs:field>
		</xs:key>
		<xs:keyref name="FKEnterprise_Owner" refer="KEnterpriseOwner">
			<xs:selector xpath="chain/enterprises/enterprise"></xs:selector>
			<xs:field xpath="@ownerId-ref"></xs:field>
		</xs:keyref>
		
		<xs:key name="KFeature">
			<xs:selector xpath="chain/enterprises/enterprise/roomTypes/roomType/features/feature"></xs:selector>
			<xs:field xpath="@fId"></xs:field>
		</xs:key>
		<xs:keyref name="FKFeatureReference_Feature" refer="KFeature">
			<xs:selector xpath="chain/enterprises/enterprise/roomTypes/roomType/descriptionWithFeature/featureReference"></xs:selector>
			<xs:field xpath="@fId-ref"></xs:field>
		</xs:keyref>

		<xs:key name="KRoomType">
			<xs:selector xpath="chain/enterprises/enterprise/roomTypes/roomType"></xs:selector>
			<xs:field xpath="@rtId"></xs:field>
		</xs:key>
		<xs:keyref name="FKRoom_RoomType" refer="KRoomType">
			<xs:selector xpath="chain/enterprises/enterprise/rooms/room"></xs:selector>
			<xs:field xpath="@rtId-reference"></xs:field>
		</xs:keyref>

		<xs:key name="KRoom">
			<xs:selector xpath="chain/enterprises/enterprise/rooms/room"></xs:selector>
			<xs:field xpath="@roomId"></xs:field>
		</xs:key>

		<xs:key name="KRate">
			<xs:selector xpath="chain/enterprises/enterprise/visit/rate"></xs:selector>
			<xs:field xpath="@rateId"></xs:field>
		</xs:key>
		
		<xs:key name="KProductCategory">
			<xs:selector xpath="chain/enterprises/visit/productCategory"></xs:selector>
			<xs:field xpath="@pcId"></xs:field>
		</xs:key>
		<xs:keyref name="FKProduct_ProductCategory" refer="KProductCategory">
			<xs:selector xpath="chain/enterprises/visit/productCategory/product"></xs:selector>
			<xs:field xpath="@pcId-ref"></xs:field>
		</xs:keyref>

  </xs:element>
  <xs:complexType name="TChain">
    <xs:complexContent>
      <xs:extension base="name">
        <xs:sequence>
        	<xs:element minOccurs="1" maxOccurs="1" ref="owner"/>
          <xs:element ref="enterprises"/>
        </xs:sequence>
        <xs:attribute name="chainId" use="required" type="xs:ID"/>
        <xs:attribute name="ownerId-ref" use="required" type="xs:IDREF"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="enterprises">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="enterprise"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="enterprise" type="TEnterprise"/>
  <xs:complexType name="TEnterprise">
    <xs:complexContent>
      <xs:extension base="name">
        <xs:sequence>
          <xs:element ref="contact"/>
          <xs:element minOccurs="1" maxOccurs="1" ref="owner"/>
          <xs:element ref="roomTypes"/>
          <xs:element ref="rooms"/>
          <xs:element ref="visit"/>
        </xs:sequence>
        <xs:attribute name="chainId-ref" use="required" type="xs:IDREF"/>
        <xs:attribute name="ownerId-ref" use="required" type="xs:IDREF"/>
        <xs:attribute name="type" use="required" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="roomTypes">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="roomType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="roomType" type="TRoomType"/>
	<xs:complexType name="TRoomType">
	  <xs:complexContent>
	    <xs:extension base="name">
	      <xs:sequence>
	        <xs:element ref="descriptionWithFeature"/>
	        <xs:element ref="features"/>
	      </xs:sequence>
	      <xs:attribute name="capacity" use="required" type="xs:integer"/>
	      <xs:attribute name="rateMultiplier" type="xs:decimal"/>
	      <xs:attribute name="rtId" use="required" type="xs:ID"/>
	    </xs:extension>
	  </xs:complexContent>
	</xs:complexType>
  
  <xs:element name="descriptionWithFeature">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="featureReference"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element> 
  <xs:element name="featureReference">
    <xs:complexType mixed="true">
      <xs:attribute name="fId-ref" use="required" type="xs:IDREF"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="features">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="2" maxOccurs="unbounded" ref="feature"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element> 
  <xs:element name="feature">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="name">
          <xs:attribute name="fId" use="required" type="xs:ID"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="rooms">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="10" maxOccurs="unbounded" ref="room"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="room" type="TRoom"/>
  <xs:complexType name="TRoom">
    <xs:attribute name="roomId" use="required" type="xs:ID"/>
    <xs:attribute name="roomNumber" use="required" type="xs:integer"/>
    <xs:attribute name="rtId-reference" use="required" type="xs:IDREF"/>
  </xs:complexType>
  
  
  <xs:element name="visit">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="rate"/>
        <xs:element ref="productCategory"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="rate">
    <xs:complexType>    	
			<xs:simpleContent>
				<xs:extension base="xs:string">
		      <xs:attribute name="amount" use="required" type="xs:integer"/>
		      <xs:attribute name="name" use="required" type="xs:string"/>
		      <xs:attribute name="rateId" use="required" type="xs:ID"/>
				</xs:extension>
			</xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="productCategory" type="TProductCategory"/>
  <xs:complexType name="TProductCategory">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" ref="product"/>
    </xs:sequence>
    <xs:attribute name="name" use="required" type="xs:string"/>
    <xs:attribute name="pcId" use="required" type="xs:ID"/>
  </xs:complexType>
  <xs:element name="product" type="TProduct"/>  
  <xs:complexType name="TProduct">
    <xs:attribute name="amount" use="required" type="xs:integer"/>
    <xs:attribute name="name" use="required" type="xs:string"/>
    <xs:attribute name="pcId-ref" use="required" type="xs:IDREF"/>
  </xs:complexType>


  <!--Common for multiple elements-->
  <xs:complexType name="name">
    <xs:sequence>
      <xs:element ref="name"/>
    </xs:sequence>   
  </xs:complexType>

  <xs:element name="name" type="xs:string"/>


  <xs:element name="owner" type="TOwner"/>
  <xs:complexType name="TOwner">
    <xs:complexContent>
      <xs:extension base="name">
        <xs:sequence>
          <xs:element ref="contact"/>
        </xs:sequence>
        <xs:attribute name="oId" use="required" type="xs:ID"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="contact" type="TContact"/>
  <xs:complexType name="TContact">
    <xs:all>
      <xs:element ref="email"/>
      <xs:element ref="phone"/>
      <xs:element ref="website"/>
      <xs:element ref="address"/>
    </xs:all>
  </xs:complexType>  
  <xs:element name="email" type="xs:string"/>
  <xs:element name="phone" type="TPhone"/>
  <xs:simpleType name="TPhone">
    <xs:restriction base="xs:string">
         <xs:pattern value="[0-9]{3} [0-9]{3} [0-9]{3}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="website" type="xs:string"/>
  <xs:element name="address" type="TAdddress"/>
  <xs:complexType name="TAdddress">
    <xs:sequence>
		  <xs:element name="line1" type="xs:string"/>
		  <xs:element name="city" type="xs:string"/>
		  <xs:element name="postalCode" type="xs:integer"/>
		  <xs:element name="country" type="xs:string"/>
		  <xs:element name="state" minOccurs="0" type="xs:string"/> 
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== bastianluk/MFFUK/XML Technologies/HW/04 - XSLT/data.xml
<?xml version="1.0" encoding="UTF-8"?>

<chain xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="data.xsd" chainId="c1" ownerId-ref="o1">
	<?php echo "Angelina&apos;s Hotels"?>
	<name>Angelina&apos;s Hotels</name>
	<owner oId="o1">
		<name>Angelina Jolie</name>
    	<contact>
    		<email>angelina@ajhotel.com</email>
    		<phone>123 456 789</phone>
    		<website>
    		    <![CDATA[
            		<a href="www.angelina.com">Chain website</a>
    			]]>
    		</website>
    		
	    	<address>
	            <line1>8433 Sunset Blvd</line1>
	            <city>LA</city>
	            <postalCode>90001</postalCode>
	            <country>USA</country>
	            <state>California</state>
	        </address>
    	</contact>
	</owner>
	
	<enterprises>
		<enterprise chainId-ref="c1" ownerId-ref="o2" type="hotel">
	    	<name>Hotel Angel Jr.</name>
	    	
	    	<contact>
	    		<email>angel-jr@ajhotel.com</email>
	    		<phone>666 666 666</phone>
    			<website>
    		 		<![CDATA[
            			<a href="www.angel-jr.com">Hotel website</a>
    				]]>
    			</website>
	    		
		    	<address>
			        <line1>8162 Melrose Ave</line1>
			        <city>LA</city>
			        <postalCode>90001</postalCode>
			        <country>USA</country>
		        </address>
	    	</contact>
	    	
	    	<owner oId="o2">
	    		<name>Angelina Jolie Jr.</name>
	    		<contact>
    				<email>angelinaJr@ajhotel.com</email>
    				<phone>987 654 321</phone>
    				<website>
    		 		    <![CDATA[
            				<a href="www.angelinajr.com">Website</a>
    					]]>
    				</website>

		    		
			    	<address>
			            <line1>200 Santa Monica Pier</line1>
			            <city>LA</city>
			            <postalCode>90001</postalCode>
			            <country>USA</country>
			        </address>
		    	</contact>
	    	</owner>
	    		
	        <roomTypes>
	            <roomType rtId="rt1" capacity="4" rateMultiplier="1.5">
					<name>Quadrouple room</name>
					<descriptionWithFeature>
						Room type for up to 4 people featuring:
						<featureReference fId-ref="f1">Small kitchen</featureReference>
						and
						<featureReference fId-ref="f2">Bath tub</featureReference>.
						Ideal for families.
					</descriptionWithFeature>
					<features>
						<feature fId="f1">
							<name>Small kitchen</name>
						</feature>
						<feature fId="f2">
							<name>Bath tub</name>
						</feature>
					</features>
	            </roomType>
	            <roomType rtId="rt2" capacity="1">
					<name>Single room</name>
					<descriptionWithFeature>
						Room type for 1 person featuring:
						<featureReference fId-ref="f3">Shower</featureReference>
						and
						<featureReference fId-ref="f4">Desk (workspace)</featureReference>.
						Ideal for traveling businessman.
					</descriptionWithFeature>
					<features>
						<feature fId="f3">
							<name>Shower</name>
						</feature>
						<feature fId="f4">
							<name>Desk (workspace)</name>
						</feature>
					</features>
	            </roomType>
	            <roomType rtId="rt3" capacity="2" rateMultiplier="1.3">
					<name>Double room</name>
					<descriptionWithFeature>
						Room type for up to 2 people featuring:
						<featureReference fId-ref="f5">Minibar</featureReference>
						and
						<featureReference fId-ref="f6">TV</featureReference>.
						Ideal for couples.
					</descriptionWithFeature>
					<features>
						<feature fId="f5">
							<name>Minibar</name>
						</feature>
						<feature fId="f6">
							<name>TV</name>
						</feature>
					</features>
	            </roomType>
	        </roomTypes>
	        <rooms>
	        	<room roomId="r1" rtId-reference="rt1" roomNumber="101"/>
	        	<room roomId="r2" rtId-reference="rt1" roomNumber="102"/>
	        	<room roomId="r3" rtId-reference="rt1" roomNumber="103"/>
	        	<room roomId="r4" rtId-reference="rt1" roomNumber="104"/>
	        	<room roomId="r5" rtId-reference="rt2" roomNumber="105"/>
	        	<room roomId="r6" rtId-reference="rt1" roomNumber="201"/>
	        	<room roomId="r7" rtId-reference="rt1" roomNumber="202"/>
	        	<room roomId="r8" rtId-reference="rt1" roomNumber="203"/>
	        	<room roomId="r9" rtId-reference="rt3" roomNumber="204"/>
	        	<room roomId="r10" rtId-reference="rt3" roomNumber="205"/>
	        </rooms>
	
	        <visit>
	            <rate rateId="rate1" name="Flexible" amount="100"/>
	            <rate rateId="rate2" name="Non-refundable" amount="90"/>
	            <productCategory pcId="pc1" name="food">
	                <product pcId-ref="pc1" name="breakfast" amount="10"/>
	                <product pcId-ref="pc1" name="lunch" amount="15"/>
	                <product pcId-ref="pc1" name="dinner" amount="20"/>
	            </productCategory>
	        </visit>
	    </enterprise>
		<enterprise chainId-ref="c1" ownerId-ref="o22" type="hotel">
	    	<name>Hotel Angel Jr. 2</name>
	    	<!--without quardrouple-->
	    	
	    	<contact>
	    		<email>angel-jr2@ajhotel.com</email>
	    		<phone>666 666 666</phone>
    			<website>
    		 		<![CDATA[
            			<a href="www.angel-jr2.com">Hotel website</a>
    				]]>
    			</website>
	    		
		    	<address>
			        <line1>8162 Melrose Ave</line1>
			        <city>San Francisco</city>
			        <postalCode>90001</postalCode>
			        <country>USA</country>
		        </address>
	    	</contact>
	    	
	    	<owner oId="o22">
	    		<name>Angelina Jolie Jr. 2</name>
	    		<contact>
    				<email>angelinaJr2@ajhotel.com</email>
    				<phone>987 654 222</phone>
    				<website>
    		 		    <![CDATA[
            				<a href="www.angelinajr2.com">Website</a>
    					]]>
    				</website>

		    		
			    	<address>
			            <line1>200 Santa Monica Pier</line1>
			            <city>LA</city>
			            <postalCode>90001</postalCode>
			            <country>USA</country>
			        </address>
		    	</contact>
	    	</owner>
	    		
	        <roomTypes>
	            <roomType rtId="rt21" capacity="3" rateMultiplier="1.5">
					<name>Triple room</name>
					<descriptionWithFeature>
						Room type for up to 3 people featuring:
						<featureReference fId-ref="f21">Small kitchen</featureReference>
						and
						<featureReference fId-ref="f22">Bath tub</featureReference>.
						Ideal for families.
					</descriptionWithFeature>
					<features>
						<feature fId="f21">
							<name>Small kitchen</name>
						</feature>
						<feature fId="f22">
							<name>Bath tub</name>
						</feature>
					</features>
	            </roomType>
	            <roomType rtId="rt22" capacity="1">
					<name>Single room</name>
					<descriptionWithFeature>
						Room type for 1 person featuring:
						<featureReference fId-ref="f23">Shower</featureReference>
						and
						<featureReference fId-ref="f24">Desk (workspace)</featureReference>.
						Ideal for traveling businessman.
					</descriptionWithFeature>
					<features>
						<feature fId="f23">
							<name>Shower</name>
						</feature>
						<feature fId="f24">
							<name>Desk (workspace)</name>
						</feature>
					</features>
	            </roomType>
	            <roomType rtId="rt23" capacity="2" rateMultiplier="1.3">
					<name>Double room</name>
					<descriptionWithFeature>
						Room type for up to 2 people featuring:
						<featureReference fId-ref="f25">Minibar</featureReference>
						and
						<featureReference fId-ref="f26">TV</featureReference>.
						Ideal for couples.
					</descriptionWithFeature>
					<features>
						<feature fId="f25">
							<name>Minibar</name>
						</feature>
						<feature fId="f26">
							<name>TV</name>
						</feature>
					</features>
	            </roomType>
	        </roomTypes>
	        <rooms>
	        	<room roomId="r21" rtId-reference="rt21" roomNumber="101"/>
	        	<room roomId="r22" rtId-reference="rt22" roomNumber="102"/>
	        	<room roomId="r23" rtId-reference="rt21" roomNumber="103"/>
	        	<room roomId="r24" rtId-reference="rt22" roomNumber="104"/>
	        	<room roomId="r25" rtId-reference="rt22" roomNumber="105"/>
	        	<room roomId="r26" rtId-reference="rt22" roomNumber="201"/>
	        	<room roomId="r27" rtId-reference="rt23" roomNumber="202"/>
	        	<room roomId="r28" rtId-reference="rt23" roomNumber="203"/>
	        	<room roomId="r29" rtId-reference="rt23" roomNumber="204"/>
	        	<room roomId="r210" rtId-reference="rt23" roomNumber="205"/>
	        </rooms>
	
	        <visit>
	            <rate rateId="rate21" name="Flexible" amount="100"/>
	            <rate rateId="rate22" name="Non-refundable" amount="90"/>
	            <productCategory pcId="pc21" name="food">
	                <product pcId-ref="pc21" name="breakfast" amount="10"/>
	                <product pcId-ref="pc21" name="lunch" amount="15"/>
	                <product pcId-ref="pc21" name="dinner" amount="20"/>
	            </productCategory>
	        </visit>
	    </enterprise>
	    <enterprise chainId-ref="c1" ownerId-ref="oNonExistant" type="hotel">
	    	<name>Breakfast and Dinner Hotel Angel Sr.</name>
	    	<!--with quardrouple type but not room-->
	    	<contact>
	    		<email>angel-jr3@ajhotel.com</email>
	    		<phone>666 666 666</phone>
    			<website>
    		 		<![CDATA[
            			<a href="www.angel-jr3.com">Hotel website</a>
    				]]>
    			</website>
	    		
		    	<address>
			        <line1>104 Montgomery St</line1>
			        <city>San Francisco</city>
			        <postalCode>94129</postalCode>
			        <country>USA</country>
			        <state>CA</state>
		        </address>
	    	</contact>
	    		
	    		<owner oId="o23">
	    		<name>Angelina Jolie Jr. 2</name>
	    		<contact>
    				<email>angelinaJr2@ajhotel.com</email>
    				<phone>987 654 222</phone>
    				<website>
    		 		    <![CDATA[
            				<a href="www.angelinajr2.com">Website</a>
    					]]>
    				</website>

		    		
			    	<address>
